name: AntiXray
version: ${project.version}
main: com.lhawk.antixray.AntiXray
author: lHawk_
description: Hides ores, structures and entities that players cannot see.
depend: [packetevents]
api-version: 1.13
folia-supported: true
commands:
  antixray:
    description: AntiXray main command
    usage: /antixray [reload|status]
    permission: antixray.admin
permissions:
  antixray.admin:
    description: Allows the /antixray commands
    default: op
